workspace:
  base: /go
  path: src/code.gitea.io/gitea

clone:
  git:
    image: plugins/git:1
    depth: 50
    tags: true

pipeline:

  docker:
    image: plugins/docker:17.12
    pull: true
    secrets: [ docker_username, docker_password ]
    repo: gitea/gitea
    tag: '${DRONE_BRANCH##release/v}-${DRONE_ARCH/\//-}'
    when:
      event: [ push ]
      branch: [ release/* ]

  docker:
    image: plugins/docker:17.12
    secrets: [ docker_username, docker_password ]
    pull: true
    repo: sapk/test-gitea
    tag: 'latest-${DRONE_ARCH/\//-}'
    when:
      event: [ push, tag ]

  docker:
    image: plugins/manifest
    secrets: [ docker_username, docker_password ]
    platforms: linux/amd64
    template: 'gitea/gitea:${DRONE_BRANCH##release/v}-OS-ARCH'
    target: 'gitea/gitea:${DRONE_BRANCH##release/v}'
    when:
      event: [ push ]
      branch: [ release/* ]

  docker:
    image: plugins/manifest
    secrets: [ docker_username, docker_password ]
    platforms: linux/amd64
    template: sapk/test-gitea:latest-OS-ARCH
    target: sapk/test-gitea:latest
    when:
      event: [ push, tag ]
